# Generated by nixos-generate-config. Prefer not to hand-edit this:
# re-running the generator will overwrite it. Put extra mount options and
# additional fileSystems (like /persist) in default.nix / impermanence.nix.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # LUKS → btrfs. Today `/` is the btrfs *top-level* (subvolid=5), not a
  # dedicated `root` subvolume. That is why rollback stays off: wiping the
  # top-level would take /home and /nix with it.
  fileSystems."/" = {
    device = "/dev/mapper/luks-5cea4be3-ce05-434b-b05d-e4ae116fc729";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."luks-5cea4be3-ce05-434b-b05d-e4ae116fc729".device =
    "/dev/disk/by-uuid/5cea4be3-ce05-434b-b05d-e4ae116fc729";

  fileSystems."/home" = {
    device = "/dev/mapper/luks-5cea4be3-ce05-434b-b05d-e4ae116fc729";
    fsType = "btrfs";
    options = [ "subvol=home" ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/luks-5cea4be3-ce05-434b-b05d-e4ae116fc729";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/90E2-C24E";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ { device = "/dev/mapper/luks-1156e5f0-2b65-421d-9c5e-a0279c671b78"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
